### ISSUE TITLE
Prioritize the usecases

### ISSUE THREAD

**Issue by JanVeen** [LCfP/Serious-Game-for-Kids#1]

**Comment by JanVeen** [comment]
@N-Wouda #1

**Comment by N-Wouda** [comment]
@LCfP/serious-logistics-games-for-kids who is assigned to this issue? @JanVeen?

**Comment by VincentVelthuizen** [comment]
We will do this together next friday

**Comment by N-Wouda** [comment]
I assume this can now be closed? It can always be re-opened, after prof Vis' evaluation is in.
