### ISSUE TITLE
Translations (EST 0,5 IMP 150)

### ISSUE THREAD

**Issue by JanVeen** [LCfP/Serious-Game-for-Kids#101]

**Comment by N-Wouda** [comment]
@LCfP/serious-logistics-games-for-kids this is for everyone: if you find a string that has not yet been translated, don't just ignore it. This PR is not a full task, but more of a last resort - a final check.

**Comment by N-Wouda** [comment]
@LCfP/serious-logistics-games-for-kids this remains critical!

**Comment by N-Wouda** [comment]
@lukko or @JanVeen would you care to devote some time to this explicitly?

**Comment by N-Wouda** [comment]
I think we got this for the most part.
