### ISSUE TITLE
Use case: I want to order a certain mix of products from the supplier  imp: 150 est: 8

### ISSUE THREAD

**Issue by JanVeen** [LCfP/Serious-Game-for-Kids#11]
Imp: 150 Est: 8
No dependency.

**Comment by N-Wouda** [comment]
I will start working on this one (have assigned myself to it). I do have an exam on the 9th and an assignment due the 7th, so that may not be done before next week. Since there is one open dependency on this, my suggestion would be to tackle the other problems first.

**Comment by N-Wouda** [comment]
Re-opened as #24 had not finished this use case in total yet. (PR #25)
