### ISSUE TITLE
Create A-B test for at the elementary school (EST 0 IMP 0)

### ISSUE THREAD

**Issue by JanVeen** [LCfP/Serious-Game-for-Kids#110]
Adding seasonality/playing in duos or separate.

**Comment by N-Wouda** [comment]
Is this the play in duos/alone one?

**Comment by N-Wouda** [comment]
Not too sure if this is solved, but since it is solely for tomorrow's demonstration, I'm closing this now (if it has not been done, there is no need to do so anymore).
