### ISSUE TITLE
Scoreboard for currently active players

### ISSUE THREAD

**Issue by N-Wouda** [LCfP/Serious-Game-for-Kids#149]
In a classroom setting, playing this game with many players is a really fun experience. Adding on top of that, the idea of a scoreboard for those currently playing is a great way to foster some competitiveness. I noticed yesterday that the kids were already quite competitive, and looked at each other (different groups) for strategies.

Projecting this while playing using _e.g._ a beamer is a great way to show progress. Furthermore, it allows the teacher to afterward discuss various successful strategies!

For this we need,

- [x] Table structure (migrations + composer file for dependencies) (#155 @lukko)
- [x] Template/views and logic

**Comment by N-Wouda** [comment]
Help wanted since,

1. This will require a back-end presence. We need to know more about the final location where the game will be hosted to select a language. I propose PHP since it's almost universally available with most hosts.

2. Think about the design of the scoreboard page. It needs to be a page that's part of the game, so e.g. `/scoreboard` as an URL. How do we keep track of which group is playing? Maybe something with a log-in system, or perhaps by IP (or they may indicate the name of the current group when prompted at start-up).

3. We need to register player names, so we should ask for them when the game first starts. I suggest Ajax calls every 30s to update the score on the server, and thus also the leaderboard.

**Comment by lukko** [comment]
1. Might be an idea to use Google Firebase for the database. They have a Javascript API, so you don't even need to use PHP.

2. For example, showing the user a login screen where they fill in a) the group-id in which they want to participate and b) a name for their group. Then the scoreboard can be shown using `/scoreboard?group=A2D5`.

3. Updating every x seconds sounds fine.

**Comment by N-Wouda** [comment]
>Might be an idea to use Google Firebase for the database. They have a Javascript API, so you don't even need to use PHP.

I had not considered using a 3rd party service for this, but since it involves data that can hardly be considered 'private', I don't see why we would not give this a go.

An added benefit is of course that this does not require us to develop anything on the back-end, which is a big plus.

>Then the scoreboard can be shown using `/scoreboard?group=A2D5`.

This is indeed what I had in mind also. We should, at just `/scoreboard`, offer them to select a list or create a new one. Quite trivial to do.

**Comment by N-Wouda** [comment]
@see #159 for implementation details.
