### ISSUE TITLE
Suggestion: use pre-defined buttons for order amounts

### ISSUE THREAD

**Issue by jonhummel-rug** [LCfP/Serious-Game-for-Kids#151]
From Hendryk Dittfeld:
Bij de bestellingsveld buttons (10, 20, 50, 100) toevoegen onder het veld waar de waarde voor elk product ingevoerd kan worden. Zo is het makkelijker en sneller om de bestelling in te voeren.

**Comment by N-Wouda** [comment]
Zie #146, @jonhummel-rug :)

**Comment by N-Wouda** [comment]
Closing this as a duplicate (suggestion is part of the more general overhaul proposed in #146).
