### ISSUE TITLE
Bug: containers do not always adhere to proper render order

### ISSUE THREAD

**Issue by N-Wouda** [LCfP/Serious-Game-for-Kids#154]
See below,

![voorbeeld containers](https://user-images.githubusercontent.com/16272507/33610353-8a5a0c12-d9cb-11e7-9cba-d1a55c5ca062.png)

**Comment by N-Wouda** [comment]
I think this may be an ajax problem with the view render order (incomplete ajax call, so the anchor may not yet exist).

**Comment by N-Wouda** [comment]
@lukko I think I've solved this. Had a hunch about this earlier today, and I figured I'd give it a try.

**Comment by lukko** [comment]
At the first reload of the game after pulling in this commit, I didn't see the 3 containers which should be there by default. Only the 'buy now' container was present. It worked during following reloads. Might have been a cache problem I guess?
