### ISSUE TITLE
Use case: I want to pause the game (IMP 100, EST 1)

### ISSUE THREAD

**Issue by JanVeen** [LCfP/Serious-Game-for-Kids#23]
Imp: 100. Est: 1

Depends on #35.

**Comment by N-Wouda** [comment]
Closing this one for now, as it is not in the upcoming sprint.

**Comment by N-Wouda** [comment]
Re-opening this one as it will be trivial to take this on in conjunction with #35.

**Comment by N-Wouda** [comment]
This is to be closed by #41.

**Comment by N-Wouda** [comment]
This has been closed in #41.
