### ISSUE TITLE
Localisation (IMP 150, EST 3)

### ISSUE THREAD

**Issue by N-Wouda** [LCfP/Serious-Game-for-Kids#32]
No dependencies. Spreadsheet ID 20.

**Comment by lukko** [comment]
Maybe we can mark the importancy numbers by labels?

**Comment by N-Wouda** [comment]
> Maybe we can mark the importancy numbers by labels?
Looks nice, but since the spreadsheet is continuously linked to the github issues, and it can be filtered well, I do not think this needs to be done at this time.

**Comment by N-Wouda** [comment]
> Maybe we can mark the importancy numbers by labels?

Looks nice, but since we also have the spreadsheet I do not think this is all that necessary at this time.
