### ISSUE TITLE
Use case: I want to run the game (IMP 150, EST 8)

### ISSUE THREAD

**Issue by N-Wouda** [LCfP/Serious-Game-for-Kids#35]
Use case: I want to run the game (IMP 150, EST 8). ID 15 in the spreadsheet.

@LCfP/serious-logistics-games-for-kids who wants to join in for pair programming on this one?

**Comment by N-Wouda** [comment]
@LCfP/serious-logistics-games-for-kids I really do expect someone to leave a comment here for pair programming.

**Comment by JanVeen** [comment]
I can join you for pair programming!
