### ISSUE TITLE
Investigate formulas for demand satisfaction (EST 1)

### ISSUE THREAD

**Issue by N-Wouda** [LCfP/Serious-Game-for-Kids#36]
Investigate formulas for demand satisfaction (EST 3). ID 16 in the spreadsheet.

This is a non-programming task.

**Comment by N-Wouda** [comment]
Who wants to tackle this non-programming issue? @JanVeen @sargis1992 @lisavancasteren?

**Comment by sargis-adikyan** [comment]
Could you please @N-Wouda   assign me to this issue ?

**Comment by N-Wouda** [comment]
Done! @sargis1992

**Comment by N-Wouda** [comment]
Updated to EST 1 for the new sprint. I assume you will not be a part of this issue any longer, @sargis1992? Then I'll remove your assignment. Thank you for your work!

**Comment by JanVeen** [comment]
This is an idea for demand satisfaction. It is work in progress, but i.m.o. substantial enough to be reviewed.

I'll convert it to formulas soon.

[Demand satisfaction.docx](https://github.com/LCfP/Serious-Game-for-Kids/files/636456/Demand.satisfaction.docx)

**Comment by N-Wouda** [comment]
Brief scan: appears useful. I do not have the time to further evaluate right now, but I think you are on the right track here.

**Comment by JanVeen** [comment]
Small update for the demand satisfaction document
[Demand satisfaction.docx](https://github.com/LCfP/Serious-Game-for-Kids/files/643509/Demand.satisfaction.docx)

**Comment by JanVeen** [comment]
Closed for now, I think the short term satisfaction per order is most important at the moment. We can later think about long term satisfaction where decisions are to be made about warehouse size and variety of products offered.
