### ISSUE TITLE
Investigate formulas for demand (EST 1)

### ISSUE THREAD

**Issue by N-Wouda** [LCfP/Serious-Game-for-Kids#37]
Investigate formulas for demand (EST 3). ID 18 in the spreadsheet.

This is a non-programming task.

**Comment by JanVeen** [comment]
Hereby I upload the 'code' that Sargis and me made.

We thought it would be useful for us to think in programming terms, so we made this file to show how we would model demand and demand satisfaction step-by-step.

The goal in this was to make the step/conversion from the 'story' we tell to the actual programming code smaller.
Note that this file is far from working programming code.

[Demand and demand satisfaction2.txt](https://github.com/LCfP/Serious-Game-for-Kids/files/622660/Demand.and.demand.satisfaction2.txt)
So this file is also relevant for issue #36 

During the sprint of tomorrow Sargis and me will elaborate more on how this file is built up.

**Comment by N-Wouda** [comment]
Updated to EST 1 for the new sprint.

**Comment by JanVeen** [comment]
Hereby I upload an idea for how to simulate demand. Let me know what you think, I will improve if necessary.

[Formulas demand2.docx](https://github.com/LCfP/Serious-Game-for-Kids/files/629735/Formulas.demand2.docx)

**Comment by JanVeen** [comment]
This is what I (and Sargis) had as an idea to simulate demand. Let me know what you think.
 
[Formulas demand2.docx](https://github.com/LCfP/Serious-Game-for-Kids/files/629743/Formulas.demand2.docx)

**Comment by N-Wouda** [comment]
Will have a closer look tomorrow

**Comment by N-Wouda** [comment]
Okay, I've gone through your document. I think you're off to a good start (there's plenty to go from here). I do worry about the complexity of having a random component in what you called 'certain demand'. Can't we just have an intercept, and a random component (perhaps two: one for smaller changes, and one for structural increases)?

Consider a linear model of the form,

`y = \beta_0 + \beta_1 * e_1 + e_2`, 
where `e_1 ~ N(time, fixed_scale_parameter)`, and `e_2 ~ N(0, other_fixed_scale_parameter)`

That way demand increases by some factor (indicated by `time`), perhaps up to a maximum, and we can account for differences between products by having a function for `beta_0` (this is where your distinctions for different products come in).

I would appreciate if your could rewrite your explanations into a more 'formula' form, similar to the above. Of course it will be more complex as some parameters may become product dependent, but in basis I feel this would be a good start. You can introduce seasonal/weekly effects as an additional parameter!

**Comment by N-Wouda** [comment]
Given that we are at the implementing stage already (with Luc's PR #62), I figure this can be closed.

If there is further reference material, please feel free to add them here still.
