### ISSUE TITLE
Create sunshine version of the game

### ISSUE THREAD

**Issue by VincentVelthuizen** [LCfP/Serious-Game-for-Kids#4]

**Comment by lisavancasteren** [comment]
[Serious game for kids - sunshine version Warehouse Game.pptx](https://github.com/LCfP/Serious-Game-for-Kids/files/570126/Serious.game.for.kids.-.sunshine.version.Warehouse.Game.pptx)

**Comment by N-Wouda** [comment]
I like it! Quite nice, and it'll surely prove productive to discuss this at the meeting tomorrow. Thank you @lisavancasteren.

**Comment by lisavancasteren** [comment]
[Serious game for kids - sunshine version Warehouse Game.pptx](https://github.com/LCfP/Serious-Game-for-Kids/files/570136/Serious.game.for.kids.-.sunshine.version.Warehouse.Game.pptx)

**Comment by lisavancasteren** [comment]
Thanks Niels! Looks very 'professional'... Will show it tomorrow!

**Comment by N-Wouda** [comment]
Thank you for your presentation yesterday @lisavancasteren!
