### ISSUE TITLE
I want to have a home screen with options (IMP 50, EST 5)

### ISSUE THREAD

**Issue by JanVeen** [LCfP/Serious-Game-for-Kids#46]
@N-Wouda:
>Would be nice to have this sprint, if anyone finds the time.
Home screen might include several of the current thing in the topbar, like language (and saving/loading?).

**Comment by N-Wouda** [comment]
If I find the time this week I'll take this one on.

**Comment by N-Wouda** [comment]
I've added a menu so far, it's more an in-game menu. Not so much a "home screen", but I think this suffices.
