### ISSUE TITLE
Create rainy version of the game

### ISSUE THREAD

**Issue by VincentVelthuizen** [LCfP/Serious-Game-for-Kids#5]

**Comment by sargis-adikyan** [comment]
I could not stand only numbers and have added some animations. 

[Warehousing game - Rainy version.pptx](https://github.com/LCfP/Serious-Game-for-Kids/files/571342/Warehousing.game.-.Rainy.version.pptx)

**Comment by N-Wouda** [comment]
Thank you for your presentation yesterday @sargis1992!
