### ISSUE TITLE
As a developer, I want a visual design that increases the usability for kids (warehouse, placing/incoming orders, racks in warehouse) (EST 8)

### ISSUE THREAD

**Issue by JanVeen** [LCfP/Serious-Game-for-Kids#54]
- [x] Warehouse
- [x] Racks/containers
- [x] Factory orders
- [x] Factory
- [x] Customers
- [x] Customer orders (?)
- [x] History/Journal entries

See also #55 for implementation, and various PRs referencing these two issues.

**Comment by N-Wouda** [comment]
@lukko and me mainly to bounce ideas off of, and see if something is doable. Consider that to be about one to two points worth, so this design part is still worth about six more.

**Comment by N-Wouda** [comment]
This is the main progress tracking issue for the PRs relating to improving the views.

This is nearly finished, at 6/7.

**Comment by N-Wouda** [comment]
Down to EST 1 for the next sprint. I'll tackle this along with the bug in the history controller.
