### ISSUE TITLE
As a child, I want the game to look fun (EST 8)

### ISSUE THREAD

**Issue by JanVeen** [LCfP/Serious-Game-for-Kids#55]

**Comment by N-Wouda** [comment]
Dependency on #54, as this is the implementation PR.

**Comment by N-Wouda** [comment]
I am under the assumption implementation will mostly be up to us, @lukko 👍

@JanVeen if you want a go at some parts of the design, feel free to self-assign!

**Comment by N-Wouda** [comment]
For an MVP, factory and warehouse are all but completed.

We still need to work on the customer, customer orders, and history views.

**Comment by N-Wouda** [comment]
Closing this. Progress can be tracked in #54! (6/7)
