### ISSUE TITLE
Implement demand satisfaction

### ISSUE THREAD

**Issue by JanVeen** [LCfP/Serious-Game-for-Kids#59]
In Dutch,

>Klanten moeten in principe ook weer kunnen weglopen als ze te lang hebben moeten wachten. Dit stond al op de originele planning voor v1.0, maar daar zijn we toen niet meer aan toegekomen (wij noemden het toen satisfaction). Dit moet wel heel grafisch kunnen worden uitgedrukt, met misschien een kort tekstje dat de klant produceert, en een kleur/emoticon die hun gemoedstoestand uitdrukt.

Dependency on #36.

**Comment by N-Wouda** [comment]
@JanVeen If you run into any problems here, feel free to ask. It is best to open a PR so we can look along on what's going on where and help out.

**Comment by N-Wouda** [comment]
The size of this will need to be increased given the new scope. It is more than `EST 1` now, but I'm removing those denominations altogether since they have no meaning in the current context.

**Comment by N-Wouda** [comment]
See https://www.flaticon.com/packs/emoji-3 for the graphical representation, @Rinnerdos.
