### ISSUE TITLE
Think about frameworks

### ISSUE THREAD

**Issue by VincentVelthuizen** [LCfP/Serious-Game-for-Kids#6]

**Comment by N-Wouda** [comment]
@lukko, what this implies is that we go looking for frameworks to structure our presentation (_e.g._, Bootstrap (4)), but also our code (_e.g._ React? jQuery?).

**Comment by lukko** [comment]
Will have a look at this in the coming days.

**Comment by lukko** [comment]
I'm using Laravel (https://laravel.com) on some personal projects and I love that framework. It's very well documented and easy to use.
It has Bootstrap support out of the box, so we can create a navigation-bar to the different games/faq's.
Also works well with Vue.js, which is similar to React (although I haven't used React myself).

**Comment by N-Wouda** [comment]
Laravel does imply a server-side presence, which as I understood it is a bit of a no-go. It should be as much client-side as possible, so PHP frameworks may not be our best bet.

Think DOM manipulation (jQuery?), style (Bootstrap?) and UI ( React?). Perhaps something with graphs/3D, like D3.js, BabylonJS or Three.js?

We do not need to decide now, as much code can be written in a framework-agnostic setting, but a short list (and general idea of pros and cons) would be nice to have before the next scrum meeting.

**Comment by VincentVelthuizen** [comment]
I think the project does not need a full PHP framework behind it yet, however keeping in mind something like Symphony or Laravel does make a lot of sense from my point of view.

So using Bootstrap and Vue, with an eye on Laravel seems fine to me. I have not worked with a JS framework so I couldn't comment on the pros/cons between them.

**Comment by lukko** [comment]
For a quick comparison, http://vuejs.org/guide/comparison.html

**Comment by N-Wouda** [comment]
Just had a look, and I like the idea of using something like this for our representation. Vue seems as good as any, and the main point would be to take the hassle out of updating the DOM. From a quick look, it seems like we should be able to connect our code with Vue handlers quite easily.

In terms of styling, Bootstrap? There's plenty to go by, and I am not too sure on which we should pick. Maybe we can hold off on fixing the styling for now?

Styling should also definitely be chosen with #4 and #5 (sunshine and rainy versions) in mind.

**Comment by lukko** [comment]
I think Bootstrap will be fine for the moment.

**Comment by N-Wouda** [comment]
I'm closing this for now, as we have sorted this out with jQuery and Bootstrap (for now).
