### ISSUE TITLE
Make a presentation to showcase the game

### ISSUE THREAD

**Issue by JanVeen** [LCfP/Serious-Game-for-Kids#66]

**Comment by JanVeen** [comment]
A draft for the presentation tomorrow

[Serious gaming for kids.pptx](https://github.com/LCfP/Serious-Game-for-Kids/files/652548/Serious.gaming.for.kids.pptx)

**Comment by N-Wouda** [comment]
Thank you @JanVeen

**Comment by N-Wouda** [comment]
I presume this has been finished? 👍
