### ISSUE TITLE
I want to get generic feedback on how to improve (EST 2)

### ISSUE THREAD

**Issue by JanVeen** [LCfP/Serious-Game-for-Kids#69]

**Comment by lukko** [comment]
I will do this.

**Comment by lukko** [comment]
Unassign me here as well.

**Comment by N-Wouda** [comment]
Are you sure?

**Comment by lukko** [comment]
Uhh.. everyone is assigning themselves at the same time. I need to get 4 points. So please assign me to #77 and this one. And unassign me from #73.

**Comment by N-Wouda** [comment]
Done

**Comment by lukko** [comment]
This one as well.

**Comment by N-Wouda** [comment]
Now stop with the difficult staffing issues! 👍

**Comment by lukko** [comment]
What do we want this to look like?

**An idea:**
At each level we add a property _days_ which will hold the number of days in which we expect the player to complete the level. If the player has not completed that level within those days, we display a popup with a hint how the player could improve to reach his goal.

Any other ideas?

**Comment by lukko** [comment]
@N-Wouda what do you think of the comment above?

**Comment by N-Wouda** [comment]
Ah, yes. I'm quite busy this week, so I think I missed this.

Seems okay to me, but we may also want to have a generic introduction on what to do where. Something like this http://eragonj.github.io/Trip.js/demo/basic/ may work well. Or else there's Intro.js, that works too. Just a small introduction guide, with optional skip step (we can use cookies to check this!).

Anyway, that's pretty much what I had in mind.
