### ISSUE TITLE
I want to implement a variety of products (including seasonality aspect) (EST 3)

### ISSUE THREAD

**Issue by JanVeen** [LCfP/Serious-Game-for-Kids#81]
Seasonality:

- [x] We need a set start date, not 'day 0'. I suggest July 1st, year 0.
- [x] Yearly seasonality.
- [x] Some products, like bananas and apples, do not have seasonality. They can be considered year-round.
- [x] Seasonality should be a function, that returns an amplifier for demand. It does not change variability (variance), just the mean.

**Comment by N-Wouda** [comment]
Seasonality:

- [ ] We need a set start date, not 'day 0'. I suggest July 1st, year 0.
- [ ] Yearly seasonality.
- [ ] Some products, like bananas and apples, do not have seasonality. They can be considered year-round.
- [ ] Seasonality should be a function, that returns an amplifier for demand. It does not change variability (variance), just the mean.

**Comment by N-Wouda** [comment]
I'm using this issue to keep track of what we need to do to implement a seasonality component.
