### ISSUE TITLE
Make overview of use cases

### ISSUE THREAD

**Issue by JanVeen** [LCfP/Serious-Game-for-Kids#9]

**Comment by JanVeen** [comment]
[usecases.xlsx](https://github.com/LCfP/Serious-Game-for-Kids/files/566929/usecases.xlsx)

In this Excel document I made an overview of what I think are useful use cases to think about for the game.

Feel free to edit/add.

**Comment by N-Wouda** [comment]
Same thing as #1 - could be closed for now I believe.
